[package]
name = "rust-crypto-lib-base"
version = "0.1.0"
edition = "2021"

[dependencies]
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
starknet-crypto = "0.7.4"

serde_json = "1.0.137"
lazy_static = "1.5.0"
num-bigint = "0.4.6"
hex = "0.4.3"
sha2 = "0.10.8"
